services:
  - name: dost-bot
    type: web
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: "uvicorn dost:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
